import { Inter } from "next/font/google";
import { AuthProvider } from "@/context/authContext";
import { StorageProvider } from "@/context/storageContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">  
      <body className={inter.className}>
        <AuthProvider>
          <StorageProvider>
          <div className="bg-black w-full h-full min-h-screen">
          {children}
          </div>
          </StorageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
